sudo: required
services:
        - docker

before_install:
        - docker build -t geovanedocker/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true geovanedocker/docker-react npm run test
