sudo: required
services:
        - docker

before_install:
        - docker build -t geovanedocker/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true geovanedocker/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-east-2" # Região onde o provider foi criado (está na url)
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-us-east-2-169343362074" # onde o app vai ficar armazenado, nesse caso, no S3 (Amazon)
        bucket_path: "docker" # diretório onde o app se está dentro do bucket
        on: # Necessário para avisar que somente o branch master deve ser monitorado
                branch: master
        # armazenados no Travis CI, gerados pelo IEM (Amazon)
        access_key_id:
                secure: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
